config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :event_logs

  resources :play_networks
  resources :play_nodes

  resources :play_invitations do
    member do
      post 'accept'
    end
    member do
      post 'reject'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: false) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :families
    end

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end
      match '/sessions'  => 'status#index', :via => :get

      resources :families

      resources :infos
      match '/info' => 'infos#last', :via => :get
      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
      end

      resources :neighbors_families
      resources :neighbors_invitations

      resources :play_networks

      resources :children
      match '/get_all_children' => 'children#index', :via => :post
      match '/get_all_playnetwork' => 'children#show_all', :via => :get
      match '/send_invite_notification' => 'children#send_invite_notification', :via => :post
      match '/send_rsvp_notification' => 'children#send_rsvp_notification', :via => :post
      match '/check_in_notification' => 'children#check_in_notification', :via => :post
      match '/come_home_notification' => 'children#come_home_notification', :via => :post
      match '/overdue_home_notification' => 'children#overdue_home_notification', :via => :post
      match '/child_arrival_notification' => 'children#child_arrival_notification', :via => :post
      match 'invited_child_arrival_notification' => 'children#invited_child_arrival_notification', :via => :post

      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
        collection do 
          post :new_message
        end
      end

      resources :friends
      resources :play_invitations
      match '/play_invitation' => 'play_invitations#last', :via => :get
      match '/accept_play_invitation/:id' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation/:id' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation/:id' => 'play_invitations#decline', :via => :post
      match '/accept_play_invitation' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation' => 'play_invitations#decline', :via => :post
    end
  end

  devise_for :users
  resources :registrations do
    match '/registrations/:id/edit(.:format)' => 'registrations#edit', :via => :post
  end
  
  resources :infos
  resources :messages do
    match '/message/:id' => 'messages#confirm', :via => :post
  end

  resources :playcelets
  resources :children

  resources :apps
  resources :supervisors
  resources :parents

  resources :places
  resources :families

  resources :neighbors_families_links
  resources :neighbors_invitations
  resources :neighbors_families

  resources :delayed_jobs

  match '/delete_all_messages_data' => 'home#delete_all_messages_data', :via => :delete

  root 'home#index'
end

app/views/shared/_children.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => "Children: #{children.count}" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Family</th>
      <th>Playcelet</th>
      <th>Color</th>
      <th>Supervisor</th>
      <th>At Place/Family</th>
      <th>Located at</th>
    </tr>
  </thead>

  <tbody>
    <% children.each do |child| %>
      <tr>
        <td><%= link_to child.name, child %></td>
        <td><%= link_to child.family.name, child.family %></td>
        <td style="background-color: #<%= child.color %>"><%= link_to child.playcelet, child_path(child), title: child.mac_address %></td>
        <td style="background-color: #<%= child.color %>"><%= link_to child.color_name, child_path(child), title: child.color %></td>
        <% supervisor = child.app.supervisor if child.app %>
        <td><%= link_to(supervisor.name, supervisor) if supervisor %></td>
        <td><%= link_to(supervisor.place.name, supervisor.place) if supervisor %></td>
        <td><%= child.located_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_children_table.html.erb
<%- model_class = Child -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <% unless skip[:family] %>
      <th><%= model_class.human_attribute_name(:family_id) %></th>
      <% end %>
      <th colspan="4"><%= model_class.human_attribute_name(:playcelet_id) %></th>
      <th><%= model_class.human_attribute_name(:checked_in) %></th>
      <th><%= model_class.human_attribute_name(:last_checked_in) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% children.each do |child| %>
      <tr>
        <td><%= link_to child.id, child_path(child) %></td>
        <td><%= link_to child.first_name, child %></td>
        <td><%= link_to child.last_name, child %></td>
        <% unless skip[:family] %>
        <td><%= link_to child.family.name, child.family %></td>
        <% end %>
        <td style="background-color: #<%= child.color %>"><%= link_to child.playcelet, child %></td>
        <td style="background-color: #<%= child.color %>"><%= link_to child.mac_address, child %></td>
        <td style="background-color: #<%= child.color %>"><%= link_to child.color, child %></td>
        <td style="background-color: #<%= child.color %>"><%= link_to child.color_name, child %></td>
        <td style="<%= "background-color: ##{child.color};" if child.app %>"><%= link_to(child.app.supervisor, child.app.supervisor) if child.app %></td>
        <td style="<%= "background-color: ##{child.color};" if child.last_app %>"><%= link_to(child.last_app.supervisor, child.last_app.supervisor) if child.last_app %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_child_path(child), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      child_path(child),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if skip[:family] %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_child_path(family_id: @family.id),
            :class => 'btn btn-primary' %>
<% else %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_child_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/shared/_invited_children.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => "Invited Children: #{invited_children.count}" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Family</th>
      <th>Playcelet</th>
      <th>Color</th>
      <th>Supervisor</th>
      <th>At Family</th>
      <th>Located at</th>
    </tr>
  </thead>

  <tbody>
    <% invited_children.each do |child| %>
      <tr>
        <td><%= link_to child.name, child %></td>
        <td><%= link_to child.family.name, child.family %></td>
        <td style="background-color: #<%= child.color %>"><%= link_to child.playcelet, child_path(child), title: child.mac_address %></td>
        <td style="background-color: #<%= child.color %>"><%= link_to child.color_name, child_path(child), title: child.color %></td>
        <td><%= link_to(child.app.supervisor.name, child.app.supervisor) if child.app %></td>
        <td><%= link_to(child.app.supervisor.family.name, child.app.supervisor.family) if child.app %></td>
        <td><%= child.located_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_located_children.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => "Located Children: #{located_children.count}" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Family</th>
      <th>Playcelet</th>
      <th>Color</th>
      <th>Supervisor</th>
      <th>Located at</th>
    </tr>
  </thead>

  <tbody>
    <% located_children.each do |child| %>
      <tr>
        <td><%= link_to child.name, child %></td>
        <td><%= link_to child.family.name, child.family %></td>
        <td style="background-color: #<%= child.color %>"><%= link_to child.playcelet, child_path(child), title: child.mac_address %></td>
        <td style="background-color: #<%= child.color %>"><%= link_to child.color_name, child_path(child), title: child.color %></td>
        <td><%= link_to(child.app.supervisor.name, child.app.supervisor) if child.app %></td>
        <td><%= child.located_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_parent.html.erb
<div>Parent: <%= link_to parent.name, parent %></div>
<div>My Family: <%= link_to family.name, family %></div>
<%= render partial: 'shared/children', locals: {children: children} %>
<%= render partial: 'shared/located_children', locals: {located_children: located_children} %>

app/views/shared/_parents.html.erb
<p>
	<h1>Parents</h1>

	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Application</th>
	      <th>User</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% parents.each do |parent| %>
	      <tr>
	        <td><%= link_to parent.name, parent %></td>
	        <td><%= link_to parent.app.name, parent.app %></td>
	        <td><%= parent.user.email %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</p>

app/views/shared/_parents_table.html.erb
<%- model_class = Parent -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
        <% unless skip[:family] %>
      <th><%= model_class.human_attribute_name(:family_id) %></th>
        <% end %>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% parents.each do |parent| %>
      <tr>
        <td><%= link_to parent.id, parent_path(parent) %></td>
        <td><%= link_to parent.first_name, parent_path(parent) %></td>
        <td><%= link_to parent.last_name, parent_path(parent) %></td>
        <% unless skip[:family] %>
        <td><%= link_to parent.family.name, parent.family %></td>
        <% end %>
        <td><%= link_to parent.user.email, parent_path(parent) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_parent_path(parent), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      parent_path(parent),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if skip[:family] %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_parent_path(family_id: @family.id),
            :class => 'btn btn-primary' %>
<% else %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_parent_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/shared/_supervisor.html.erb
<div>Supervisor: <%= link_to supervisor.name, supervisor %></div>
<div>My Place: <%= link_to place.name, place %></div>
<%= render partial: 'shared/located_children', locals: {located_children: located_children} %>

app/views/shared/_supervisors.html.erb
<p>
	<h1>Supervisors</h1>

	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Application</th>
	      <th>User</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% supervisors.each do |supervisor| %>
	      <tr>
	        <td><%= link_to supervisor.name, supervisor %></td>
	        <td><%= link_to supervisor.app.name, supervisor.app %></td>
	        <td><%= supervisor.user.email %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</p>

app/views/shared/_user.html.erb
<% if @user.parent? %>
  <strong>Parent Details:</strong>
  <%= render partial: 'shared/parent', locals: {parent: @parent, family: @family, children: @children, located_children: @located_children} %>
<% else %>
  <strong>Supervisor Details:</strong>
  <%= render partial: 'shared/supervisor', locals: {supervisor: @supervisor, place: @place, located_children: @located_children} %>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if resource and resource.errors and (resource.errors.count > 0) %>
  <div class="alert alert-danger">
    <a class="close" data-dismiss="alert">&times;<a>
    <strong><%= pluralize(resource.errors.count,"error") %> validation problems found.</strong>
    <ul>
    <% resource.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  </div>
<% end %>