config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :event_logs

  resources :play_networks
  resources :play_nodes

  resources :play_invitations do
    member do
      post 'accept'
    end
    member do
      post 'reject'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: false) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :families
    end

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end
      match '/sessions'  => 'status#index', :via => :get

      resources :families

      resources :infos
      match '/info' => 'infos#last', :via => :get
      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
      end

      resources :neighbors_families
      resources :neighbors_invitations

      resources :play_networks

      resources :children
      match '/get_all_children' => 'children#index', :via => :post
      match '/get_all_playnetwork' => 'children#show_all', :via => :get
      match '/send_invite_notification' => 'children#send_invite_notification', :via => :post
      match '/send_rsvp_notification' => 'children#send_rsvp_notification', :via => :post
      match '/check_in_notification' => 'children#check_in_notification', :via => :post
      match '/come_home_notification' => 'children#come_home_notification', :via => :post
      match '/overdue_home_notification' => 'children#overdue_home_notification', :via => :post
      match '/child_arrival_notification' => 'children#child_arrival_notification', :via => :post
      match 'invited_child_arrival_notification' => 'children#invited_child_arrival_notification', :via => :post

      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
        collection do 
          post :new_message
        end
      end

      resources :friends
      resources :play_invitations
      match '/play_invitation' => 'play_invitations#last', :via => :get
      match '/accept_play_invitation/:id' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation/:id' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation/:id' => 'play_invitations#decline', :via => :post
      match '/accept_play_invitation' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation' => 'play_invitations#decline', :via => :post
    end
  end

  devise_for :users
  resources :registrations do
    match '/registrations/:id/edit(.:format)' => 'registrations#edit', :via => :post
  end
  
  resources :infos
  resources :messages do
    match '/message/:id' => 'messages#confirm', :via => :post
  end

  resources :playcelets
  resources :children

  resources :apps
  resources :supervisors
  resources :parents

  resources :places
  resources :families

  resources :neighbors_families_links
  resources :neighbors_invitations
  resources :neighbors_families

  resources :delayed_jobs

  match '/delete_all_messages_data' => 'home#delete_all_messages_data', :via => :delete

  root 'home#index'
end

app/models/delayed_job.rb
class DelayedJob < ActiveRecord::Base

end

app/controllers/delayed_jobs_controller.rb
class DelayedJobsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_delayed_job, only: [:show]
  before_action :get_params, only: [:index]

  # GET /delayed_jobs
  # GET /delayed_jobs.json
  def index
    if @type == 'queued'
      @delayed_jobs = DelayedJob.where(run_at: nil).order('id DESC').paginate(:page => @page,:per_page => @per_page)
    elsif @type == 'run'
      @delayed_jobs = DelayedJob.where.not(run_at: nil).order('id DESC').paginate(:page => @page,:per_page => @per_page)
    elsif @type == 'failed'
      @delayed_jobs = DelayedJob.where.not(last_error: nil).order('id DESC').paginate(:page => @page,:per_page => @per_page)
    elsif @type == 'success'
      @delayed_jobs = DelayedJob.where(last_error: nil).order('id DESC').paginate(:page => @page,:per_page => @per_page)
    else
      @delayed_jobs = DelayedJob.all.order('id DESC').paginate(:page => @page,:per_page => @per_page)
    end
  end

  # GET /delayed_jobs/1
  # GET /delayed_jobs/1.json
  def show
  end

  private
    def authenticate_admin!
      user_signed_in? && current_user.admin?
    end

    def get_params
      @type = params[:type]
      @page = params[:page]
      @per_page = params[:per_page]
      if @per_page.blank?
        @per_page = @timestamp ? 10000 : 10
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_delayed_job
      @delayed_job = DelayedJob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delayed_job_params
      params[:delayed_job]
    end
end

app/helpers/delayed_jobs_helper.rb
module DelayedJobsHelper
  def last_error_tag(delayed_job)
  	if delayed_job.last_error
  	  delayed_job.last_error.split("\n").join("</br>")
  	else
  	  ''
  	end.html_safe
  end
end

app/views/delayed_jobs/index.html.erb
<h1>Listing delayed_jobs</h1>


<%- model_class = DelayedJob -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="list-header">
  <%= link_to 'All', delayed_jobs_path, class: 'btn btn-mini btn-primary' %>
  <%= link_to 'Failed', delayed_jobs_path(type: :failed), class: 'btn btn-mini btn-danger' %>
  <%= link_to 'Success', delayed_jobs_path(type: :success), class: 'btn btn-mini' %>
  <%= link_to 'Queued', delayed_jobs_path(type: :queued), class: 'btn btn-mini' %>
  <%= link_to 'Run', delayed_jobs_path(type: :run), class: 'btn btn-mini' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:attempts) %></th>
      <th><%= model_class.human_attribute_name(:handler) %></th>
      <th><%= model_class.human_attribute_name(:last_error) %></th>
      <th><%= model_class.human_attribute_name(:run_at) %></th>
      <th><%= model_class.human_attribute_name(:locked_at) %></th>
      <th><%= model_class.human_attribute_name(:failed_at) %></th>
      <th><%= model_class.human_attribute_name(:locked_by) %></th>
      <th><%= model_class.human_attribute_name(:queue) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @delayed_jobs.each do |delayed_job| %>
      <tr>
        <td><%= link_to delayed_job.id, delayed_job_path(delayed_job) %></td>
        <td><%= link_to delayed_job.priority, delayed_job_path(delayed_job) %></td>
        <td><%= link_to delayed_job.attempts, delayed_job_path(delayed_job) %></td>
        <td><%= link_to delayed_job.handler ? delayed_job.handler[0..99] : '', delayed_job_path(delayed_job) %></td>
        <td><%= link_to delayed_job.last_error ? delayed_job.last_error[0..99] : '', delayed_job_path(delayed_job) %></td>
        <td><%=l_with_time_zone(delayed_job.run_at) if delayed_job.run_at %></td>
        <td><%=l_with_time_zone(delayed_job.failed_at) if delayed_job.failed_at %></td>
        <td><%=l_with_time_zone(delayed_job.locked_at) if delayed_job.locked_at %></td>
        <td><%= link_to delayed_job.locked_by || '' , delayed_job_path(delayed_job) %></td>
        <td><%= link_to delayed_job.queue || '', delayed_job_path(delayed_job) %></td>
        <td><%=l_with_time_zone(delayed_job.created_at) if delayed_job.created_at %></td>
        <td><%=l_with_time_zone(delayed_job.updated_at) if delayed_job.updated_at%></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      delayed_job_path(delayed_job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @delayed_jobs, renderer: BootstrapPagination::Rails %>

app/views/delayed_jobs/show.html.erb
<%- model_class = DelayedJob -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:id) %>:</strong></dt>
  <dd><%= @delayed_job.id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:priority) %>:</strong></dt>
  <dd><%= @delayed_job.priority %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attempts) %>:</strong></dt>
  <dd><%= @delayed_job.attempts %></dd>
  <dt><strong><%= model_class.human_attribute_name(:handler) %>:</strong></dt>
  <dd><%= @delayed_job.handler %></dd>
  <dt><strong><%= model_class.human_attribute_name(:run_at) %>:</strong></dt>
  <dd><%= @delayed_job.run_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_error) %>:</strong></dt>
  <dd><%= last_error_tag @delayed_job %></dd>
  <dt><strong><%= model_class.human_attribute_name(:failed_at) %>:</strong></dt>
  <dd><%= @delayed_job.failed_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:locked_at) %>:</strong></dt>
  <dd><%= @delayed_job.failed_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:locked_by) %>:</strong></dt>
  <dd><%= @delayed_job.locked_by %></dd>
  <dt><strong><%= model_class.human_attribute_name(:queue) %>:</strong></dt>
  <dd><%= @delayed_job.queue %></dd>
  <dt><strong><%= model_class.human_attribute_name(:queue) %>:</strong></dt>
  <dd><%= @delayed_job.queue %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @delayed_job.created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:updated_at) %>:</strong></dt>
  <dd><%= @delayed_job.updated_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              delayed_jobs_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              delayed_job_path(@delayed_job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>