config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :event_logs

  resources :play_networks
  resources :play_nodes

  resources :play_invitations do
    member do
      post 'accept'
    end
    member do
      post 'reject'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: false) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :families
    end

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end
      match '/sessions'  => 'status#index', :via => :get

      resources :families

      resources :infos
      match '/info' => 'infos#last', :via => :get
      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
      end

      resources :neighbors_families
      resources :neighbors_invitations

      resources :play_networks

      resources :children
      match '/get_all_children' => 'children#index', :via => :post
      match '/get_all_playnetwork' => 'children#show_all', :via => :get
      match '/send_invite_notification' => 'children#send_invite_notification', :via => :post
      match '/send_rsvp_notification' => 'children#send_rsvp_notification', :via => :post
      match '/check_in_notification' => 'children#check_in_notification', :via => :post
      match '/come_home_notification' => 'children#come_home_notification', :via => :post
      match '/overdue_home_notification' => 'children#overdue_home_notification', :via => :post
      match '/child_arrival_notification' => 'children#child_arrival_notification', :via => :post
      match 'invited_child_arrival_notification' => 'children#invited_child_arrival_notification', :via => :post

      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
        collection do 
          post :new_message
        end
      end

      resources :friends
      resources :play_invitations
      match '/play_invitation' => 'play_invitations#last', :via => :get
      match '/accept_play_invitation/:id' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation/:id' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation/:id' => 'play_invitations#decline', :via => :post
      match '/accept_play_invitation' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation' => 'play_invitations#decline', :via => :post
    end
  end

  devise_for :users
  resources :registrations do
    match '/registrations/:id/edit(.:format)' => 'registrations#edit', :via => :post
  end
  
  resources :infos
  resources :messages do
    match '/message/:id' => 'messages#confirm', :via => :post
  end

  resources :playcelets
  resources :children

  resources :apps
  resources :supervisors
  resources :parents

  resources :places
  resources :families

  resources :neighbors_families_links
  resources :neighbors_invitations
  resources :neighbors_families

  resources :delayed_jobs

  match '/delete_all_messages_data' => 'home#delete_all_messages_data', :via => :delete

  root 'home#index'
end

app/models/play_network.rb
class PlayNetwork < ActiveRecord::Base
  has_many :play_nodes
  has_many :children, through: :play_nodes
  validates :name, presence: true

  def to_s
    name
  end

  def as_json(options = {})
    result = {
      id: id,
      name: name,
    }
    result
  end
end

app/controllers/api/v1/play_networks_controller.rb
class Api::V1::PlayNetworksController < ApplicationController
  before_action :set_play_network, only: [:show, :edit, :update, :destroy]
  before_action :get_params, only: :index

  # GET /play_networks
  # GET /play_networks.json
  def index
    if current_user.admin?
      @play_networks = PlayNetwork.all
    elsif current_user.parent?
      if @child
        EventLog.getPlayNetworks(current_user, nil, child1_id: @child.id)
        @play_networks = @child.play_networks
      else
        EventLog.getPlayNetworks(current_user)
        @play_networks = current_user.family.play_networks
      end
    else
      @play_networks = []
    end
  end

  # GET /play_networks/1
  # GET /play_networks/1.json
  def show 
  end  

  # GET /play_networks/new
  def new
    @play_network = PlayNetwork.new
  end

  # GET /play_networks/1/edit
  def edit
  end

  # POST /play_networks
  # POST /play_networks.json
  def create
    @play_network = PlayNetwork.new(play_network_params)

    respond_to do |format|
      if @play_network.save
        format.html { redirect_to @play_network, notice: 'Play network was successfully created.' }
        format.json { render :show, status: :created, location: @play_network }
      else
        format.html { render :new }
        format.json { render json: @play_network.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /play_networks/1
  # PATCH/PUT /play_networks/1.json
  def update
    respond_to do |format|
      if @play_network.update(play_network_params)
        format.html { redirect_to @play_network, notice: 'Play network was successfully updated.' }
        format.json { render :show, status: :ok, location: @play_network }
      else
        format.html { render :edit }
        format.json { render json: @play_network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /play_networks/1
  # DELETE /play_networks/1.json
  def destroy
    @play_network.destroy
    respond_to do |format|
      format.html { redirect_to play_networks_url, notice: 'Play network was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play_network
      @play_network = PlayNetwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_network_params
      params.require(:play_network).permit(:name)
    end

    def get_params
      @child_id = params[:child_id] || params[:child]
      @play_network_id = params[:play_network_id] || params[:play_network]
      if @child_id
        @child = Child.find(@child_id)
      end
    end
end

app/controllers/play_networks_controller.rb
class PlayNetworksController < ApplicationController
  before_action :set_play_network, only: [:show, :edit, :update, :destroy]
  before_action :get_params, only: :index

  # GET /play_networks
  # GET /play_networks.json
  def index
    if current_user.admin?
      @play_networks = PlayNetwork.all
    elsif current_user.parent?
      if @child
        EventLog.getPlayNetworks(current_user, nil, child1_id: @child.id)
        @play_networks = @child.play_networks
      else
        EventLog.getPlayNetworks(current_user)
        @play_networks = current_user.family.play_networks
      end
    else
      @play_networks = []
    end
  end

  # GET /play_networks/1
  # GET /play_networks/1.json
  def show
  end

  # GET /play_networks/new
  def new
    @play_network = PlayNetwork.new
  end

  # GET /play_networks/1/edit
  def edit
  end

  # POST /play_networks
  # POST /play_networks.json
  def create
    @play_network = PlayNetwork.new(play_network_params)

    respond_to do |format|
      if @play_network.save
        format.html { redirect_to @play_network, notice: 'Play network was successfully created.' }
        format.json { render :show, status: :created, location: @play_network }
      else
        format.html { render :new }
        format.json { render json: @play_network.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /play_networks/1
  # PATCH/PUT /play_networks/1.json
  def update
    respond_to do |format|
      if @play_network.update(play_network_params)
        format.html { redirect_to @play_network, notice: 'Play network was successfully updated.' }
        format.json { render :show, status: :ok, location: @play_network }
      else
        format.html { render :edit }
        format.json { render json: @play_network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /play_networks/1
  # DELETE /play_networks/1.json
  def destroy
    @play_network.destroy
    respond_to do |format|
      format.html { redirect_to play_networks_url, notice: 'Play network was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play_network
      @play_network = PlayNetwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_network_params
      params.require(:play_network).permit(:name)
    end

    def get_params
      @child_id = params[:child_id] || params[:child]
      @play_network_id = params[:play_network_id] || params[:play_network]
      if @child_id
        @child = Child.find(@child_id)
      end
    end
end

app/helpers/api/v1/play_networks_helper.rb
module Api::V1::PlayNetworksHelper
end

app/helpers/play_networks_helper.rb
module PlayNetworksHelper
end

app/views/play_networks/_form.html.erb
<%= form_for @play_network, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                play_networks_path, :class => 'btn' %>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= PlayNode.human_attribute_name(:id) %></th>
      <th><%= PlayNode.human_attribute_name(:child_id) %></th>
      <th><%= PlayNode.human_attribute_name(:playcelet_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @play_network.play_nodes.each do |play_node| %>
      <tr>
        <td><%= link_to play_node.id, play_node_path(play_node) %></td>
        <td style="background-color: #<%= play_node.child.color %>"><%= link_to play_node.child.name, play_node.child %></td>
        <td style="background-color: #<%= play_node.child.color %>"><%= link_to play_node.child.playcelet, play_node.child %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_play_node_path(play_node), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      play_node_path(play_node),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="form-actions">
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_play_node_path(play_network_id: @play_network.id),
            :class => 'btn btn-primary' %>
</div>

app/views/play_networks/edit.html.erb
<%- model_class = PlayNetwork -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/play_networks/index.html.erb
<%- model_class = PlayNetwork -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @play_networks.each do |play_network| %>
      <tr>
        <td><%= link_to play_network.id, play_network_path(play_network) %></td>
        <td><%= link_to play_network.name, play_network %></td>
        <td><%=l_with_time_zone play_network.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_play_network_path(play_network), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      play_network_path(play_network),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_play_network_path,
            :class => 'btn btn-primary' %>

app/views/play_networks/new.html.erb
<%- model_class = PlayNetwork -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/play_networks/show.html.erb
<%- model_class = PlayNetwork -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @play_network.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              play_networks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_play_network_path(@play_network), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              play_network_path(@play_network),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= PlayNode.human_attribute_name(:id) %></th>
      <th><%= PlayNode.human_attribute_name(:child_id) %></th>
      <th><%= PlayNode.human_attribute_name(:playcelet_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @play_network.play_nodes.each do |play_node| %>
      <tr>
        <td><%= link_to play_node.id, play_node_path(play_node) %></td>
        <td style="background-color: #<%= play_node.child.color %>"><%= link_to play_node.child.name, play_node.child %></td>
        <td style="background-color: #<%= play_node.child.color %>"><%= link_to play_node.child.playcelet, play_node.child %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_play_node_path(play_node), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      play_node_path(play_node),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="form-actions">
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_play_node_path(play_network_id: @play_network.id),
            :class => 'btn btn-primary' %>
</div>