config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :event_logs

  resources :play_networks
  resources :play_nodes

  resources :play_invitations do
    member do
      post 'accept'
    end
    member do
      post 'reject'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: false) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :families
    end

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end
      match '/sessions'  => 'status#index', :via => :get

      resources :families

      resources :infos
      match '/info' => 'infos#last', :via => :get
      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
      end

      resources :neighbors_families
      resources :neighbors_invitations

      resources :play_networks

      resources :children
      match '/get_all_children' => 'children#index', :via => :post
      match '/get_all_playnetwork' => 'children#show_all', :via => :get
      match '/send_invite_notification' => 'children#send_invite_notification', :via => :post
      match '/send_rsvp_notification' => 'children#send_rsvp_notification', :via => :post
      match '/check_in_notification' => 'children#check_in_notification', :via => :post
      match '/come_home_notification' => 'children#come_home_notification', :via => :post
      match '/overdue_home_notification' => 'children#overdue_home_notification', :via => :post
      match '/child_arrival_notification' => 'children#child_arrival_notification', :via => :post
      match 'invited_child_arrival_notification' => 'children#invited_child_arrival_notification', :via => :post

      resources :messages do
        match '/message/:id' => 'messages#confirm', :via => :post
        collection do 
          post :new_message
        end
      end

      resources :friends
      resources :play_invitations
      match '/play_invitation' => 'play_invitations#last', :via => :get
      match '/accept_play_invitation/:id' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation/:id' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation/:id' => 'play_invitations#decline', :via => :post
      match '/accept_play_invitation' => 'play_invitations#accept', :via => :post
      match '/cancel_play_invitation' => 'play_invitations#cancel', :via => :post
      match '/decline_play_invitation' => 'play_invitations#decline', :via => :post
    end
  end

  devise_for :users
  resources :registrations do
    match '/registrations/:id/edit(.:format)' => 'registrations#edit', :via => :post
  end
  
  resources :infos
  resources :messages do
    match '/message/:id' => 'messages#confirm', :via => :post
  end

  resources :playcelets
  resources :children

  resources :apps
  resources :supervisors
  resources :parents

  resources :places
  resources :families

  resources :neighbors_families_links
  resources :neighbors_invitations
  resources :neighbors_families

  resources :delayed_jobs

  match '/delete_all_messages_data' => 'home#delete_all_messages_data', :via => :delete

  root 'home#index'
end

app/controllers/api/v1/infos_controller.rb
class Api::V1::InfosController < Api::BaseController
  protect_from_forgery with: :null_session
  
  before_action :get_params, only: [:index, :last]
  before_action :set_info, only: [:show, :edit, :update, :destroy]
  before_action :read_infos, only: [:index, :last]
  respond_to :json

  # GET /infos
  # GET /infos.json
  def index
    EventLog.getInfos(current_user)
  end

  # GET /api/info
  # GET /api/info
  # GET /api/info/1.json
  def last
    EventLog.getLastInfo(current_user, @info)
    render json: @infos.first.as_json(), status: 200
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    if @info.save
      render :show, status: :created, location: @info
    else
      render json: @info.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    if @info.update(info_params)
      render :show, status: :ok, location: @info
    else
      render json: @info.errors, status: :unprocessable_entity
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    def read_infos
      if current_user.admin?
        @infos = Info.all.by_message_type(@message_types).by_display_type(@display_type).recent.after(@timestamp).paginate(:page => @page,:per_page => @per_page).to_a
      elsif current_user.parent?
        @infos = current_user.parent.infos_by_type(@message_types).by_display_type(@display_type).recent.after(@timestamp).paginate(:page => @page,:per_page => @per_page).to_a
      elsif current_user.supervisor?
        @infos = current_user.supervisor.infos_by_type(@message_types).by_display_type(@display_type).recent.after(@timestamp).paginate(:page => @page,:per_page => @per_page).to_a
      else
        @infos = []
      end
      @infos.each{|i| i.mark_delivered!} if !@infos.blank? && @mobile_device
    end

    def get_params
      @mobile_device = params[:device] || params[:device_id]
      @display_type = params[:display_type]
      @message_type = params[:types] || params[:type]
      @message_types = @message_type && @message_type.include?(',') ? @message_type.split(',') : @message_type
      @page = params[:page]
      @timestamp = params[:timestamp].blank? ? nil : Time.at(params[:timestamp].to_i)
      @per_page = !params[:per_page].blank? ? params[:per_page] : (params[:action] == 'last') ? 1 : @timestamp ? 10000 : 10
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:message_type, :timestamp, :received_at, :app_id, :playcelet_id)
    end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]
  before_action :get_params, only: [:index, :last]

  # GET /infos
  # GET /infos.json
  def index
    if current_user.admin?
      @infos = Info.all.by_message_type(@message_types).by_display_type(@display_type).recent.after(@timestamp).paginate(:page => @page,:per_page => @per_page)
    elsif current_user.parent?
      @infos = current_user.parent.infos_by_type(@message_types).by_display_type(@display_type).recent.after(@timestamp).paginate(:page => @page,:per_page => @per_page)
    elsif current_user.supervisor?
      @infos = current_user.supervisor.infos_by_type(@message_types).by_message_type(@message_types).by_display_type(@display_type).recent.after(@timestamp).paginate(:page => @page,:per_page => @per_page)
    else
      @infos = []
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_params
      @message_type = params[:types] || params[:type]
      @display_type = params[:display_type]
      @message_types = @message_type && @message_type.include?(',') ? @message_type.split(',') : @message_type
      @page = params[:page]
      @timestamp = params[:timestamp].blank? ? nil : Time.at(params[:timestamp].to_i)
      @per_page = params[:per_page]
      if @per_page.blank?
        @per_page = @timestamp ? 10000 : 10
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:message_type, :timestamp, :received_at, :app_id, :playcelet_id)
    end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_for @info, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :child_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :child_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :app_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :app_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :message_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :message_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :message_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :message_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :timestamp, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :timestamp, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :received_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :received_at, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                infos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<%- model_class = Info -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/infos/index.html.erb
<%- model_class = Info -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:parent) %></th>
      <th><%= model_class.human_attribute_name(:child_id) %></th>
      <th><%= model_class.human_attribute_name(:recipient_child_id) %></th>
      <th><%= model_class.human_attribute_name(:message_type) %></th>
      <th><%= model_class.human_attribute_name(:display_type) %></th>
      <th><%= model_class.human_attribute_name(:color) %></th>
      <th><%= model_class.human_attribute_name(:light_mode) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:message_text) %></th>
      <!--th><%= model_class.human_attribute_name(:received_at) %></th-->
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= link_to info.id, info_path(info) %></td>
        <td><%= link_to info.get_supervisor, info.get_supervisor %></td>
        <td style="<%= "background-color: ##{info.child.color};" if info.child %>"><%= link_to(info.child.name, child_path(info.child), title: info.child.playcelet_id) if info.child %></td>
        <td style="<%= "background-color: ##{info.recipient_child.color};" if info.recipient_child %>"><%= link_to(info.recipient_child.name, child_path(info.recipient_child), title: info.recipient_child.playcelet_id) if info.recipient_child %></td>
        <td><%= info.message_type %></td>
        <td><%= info.display_type %></td>
        <td style="<%= "background-color: ##{info.color};" %>">#<%= info.color %></td>
        <td><%= info.light_mode %></td>
        <td><%= info.status %></td>
        <td><%= info.message_text ? info.message_text[0..50] : '' %></td>
        <!--td><%= info.received_at %></td-->
        <td><%=l_with_time_zone info.created_at %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      info_path(info),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @infos, renderer: BootstrapPagination::Rails %>

app/views/infos/new.html.erb
<%- model_class = Info -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/infos/show.html.erb
<%- model_class = Info -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:child_id) %>:</strong></dt>
  <dd><%= link_to @info.child, @info.child %></dd>
  <dt><strong><%= model_class.human_attribute_name(:parent) %>:</strong></dt>
  <dd><%= link_to @info.get_supervisor, @info.get_supervisor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:message_id) %>:</strong></dt>
  <dd><%= @info.message_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:message_type) %>:</strong></dt>
  <dd><%= @info.message_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @info.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:timestamp) %>:</strong></dt>
  <dd><%= @info.timestamp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:received_at) %>:</strong></dt>
  <dd><%= @info.received_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              infos_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              info_path(@info),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>